/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Master_H
#define Master_H

#include <thrift/TDispatchProcessor.h>
#include "master_types.h"



class MasterIf {
 public:
  virtual ~MasterIf() {}
  virtual void Heartbeat(const MachineInfo& info) = 0;
  virtual int32_t AddVC(const VCInfo& vc_info) = 0;
};

class MasterIfFactory {
 public:
  typedef MasterIf Handler;

  virtual ~MasterIfFactory() {}

  virtual MasterIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MasterIf* /* handler */) = 0;
};

class MasterIfSingletonFactory : virtual public MasterIfFactory {
 public:
  MasterIfSingletonFactory(const boost::shared_ptr<MasterIf>& iface) : iface_(iface) {}
  virtual ~MasterIfSingletonFactory() {}

  virtual MasterIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MasterIf* /* handler */) {}

 protected:
  boost::shared_ptr<MasterIf> iface_;
};

class MasterNull : virtual public MasterIf {
 public:
  virtual ~MasterNull() {}
  void Heartbeat(const MachineInfo& /* info */) {
    return;
  }
  int32_t AddVC(const VCInfo& /* vc_info */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Master_Heartbeat_args__isset {
  _Master_Heartbeat_args__isset() : info(false) {}
  bool info;
} _Master_Heartbeat_args__isset;

class Master_Heartbeat_args {
 public:

  Master_Heartbeat_args() {
  }

  virtual ~Master_Heartbeat_args() throw() {}

  MachineInfo info;

  _Master_Heartbeat_args__isset __isset;

  void __set_info(const MachineInfo& val) {
    info = val;
  }

  bool operator == (const Master_Heartbeat_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const Master_Heartbeat_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Master_Heartbeat_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Master_Heartbeat_pargs {
 public:


  virtual ~Master_Heartbeat_pargs() throw() {}

  const MachineInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Master_Heartbeat_result {
 public:

  Master_Heartbeat_result() {
  }

  virtual ~Master_Heartbeat_result() throw() {}


  bool operator == (const Master_Heartbeat_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Master_Heartbeat_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Master_Heartbeat_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Master_Heartbeat_presult {
 public:


  virtual ~Master_Heartbeat_presult() throw() {}


  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Master_AddVC_args__isset {
  _Master_AddVC_args__isset() : vc_info(false) {}
  bool vc_info;
} _Master_AddVC_args__isset;

class Master_AddVC_args {
 public:

  Master_AddVC_args() {
  }

  virtual ~Master_AddVC_args() throw() {}

  VCInfo vc_info;

  _Master_AddVC_args__isset __isset;

  void __set_vc_info(const VCInfo& val) {
    vc_info = val;
  }

  bool operator == (const Master_AddVC_args & rhs) const
  {
    if (!(vc_info == rhs.vc_info))
      return false;
    return true;
  }
  bool operator != (const Master_AddVC_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Master_AddVC_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Master_AddVC_pargs {
 public:


  virtual ~Master_AddVC_pargs() throw() {}

  const VCInfo* vc_info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Master_AddVC_result__isset {
  _Master_AddVC_result__isset() : success(false) {}
  bool success;
} _Master_AddVC_result__isset;

class Master_AddVC_result {
 public:

  Master_AddVC_result() : success(0) {
  }

  virtual ~Master_AddVC_result() throw() {}

  int32_t success;

  _Master_AddVC_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const Master_AddVC_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Master_AddVC_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Master_AddVC_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Master_AddVC_presult__isset {
  _Master_AddVC_presult__isset() : success(false) {}
  bool success;
} _Master_AddVC_presult__isset;

class Master_AddVC_presult {
 public:


  virtual ~Master_AddVC_presult() throw() {}

  int32_t* success;

  _Master_AddVC_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MasterClient : virtual public MasterIf {
 public:
  MasterClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  MasterClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Heartbeat(const MachineInfo& info);
  void send_Heartbeat(const MachineInfo& info);
  void recv_Heartbeat();
  int32_t AddVC(const VCInfo& vc_info);
  void send_AddVC(const VCInfo& vc_info);
  int32_t recv_AddVC();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MasterProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MasterIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MasterProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Heartbeat(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddVC(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MasterProcessor(boost::shared_ptr<MasterIf> iface) :
    iface_(iface) {
    processMap_["Heartbeat"] = &MasterProcessor::process_Heartbeat;
    processMap_["AddVC"] = &MasterProcessor::process_AddVC;
  }

  virtual ~MasterProcessor() {}
};

class MasterProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MasterProcessorFactory(const ::boost::shared_ptr< MasterIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MasterIfFactory > handlerFactory_;
};

class MasterMultiface : virtual public MasterIf {
 public:
  MasterMultiface(std::vector<boost::shared_ptr<MasterIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MasterMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MasterIf> > ifaces_;
  MasterMultiface() {}
  void add(boost::shared_ptr<MasterIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Heartbeat(const MachineInfo& info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Heartbeat(info);
    }
    ifaces_[i]->Heartbeat(info);
  }

  int32_t AddVC(const VCInfo& vc_info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddVC(vc_info);
    }
    return ifaces_[i]->AddVC(vc_info);
  }

};



#endif
