// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Master.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ;

class MasterHandler : virtual public MasterIf {
 public:
  MasterHandler() {
    // Your initialization goes here
  }

  void Heartbeat(const MachineInfo& info) {
    // Your implementation goes here
    printf("Heartbeat\n");
  }

  int32_t AddVC(const VCInfo& vc_info) {
    // Your implementation goes here
    printf("AddVC\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MasterHandler> handler(new MasterHandler());
  shared_ptr<TProcessor> processor(new MasterProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

